#%RAML 1.0 Library

types:

  CorrelationAssaySelfUnipartitenetworkPostRequest:
    type: DataPluginRequestBase
    properties:
      computeConfig: CorrelationAssaySelfConfig
      config: CorrelationNetworkSpec