version: "3.5"

services:

  subsetting:
    image: veupathdb/eda-subsetting:${SUBSETTING_TAG:-latest}
    networks:
      internal:
        aliases:
          - subsetting-internal
      external:
      monitoring-ext:
      traefik:
    volumes:
      - type: bind
        source: ${MACHINE_BINARY_FILES_DIR:-/var/www/Common/apiSiteFilesMirror/webServices}
        target: ${SERVICE_BINARY_FILES_DIR:-/binaryFiles}
        read_only: true
    environment:
      # port providing the service
      SERVER_PORT: ${SUBSETTING_SERVER_PORT:-8080}

      # URLs of required services
      DATASET_ACCESS_SERVICE_URL: ${DATASET_ACCESS_SERVICE_URL:-http://dataset-access-internal}:${DATASET_ACCESS_SERVER_PORT:-8080}

      # Map-reduce subsetting method configuraton
      BINARY_FILES_DIR: ${SERVICE_BINARY_FILES_DIR:-/binaryFiles}
      DB_BUILD: ${DB_BUILD}
      AVAILABLE_BINARY_FILES_PATHS: ${AVAILABLE_BINARY_FILES_PATHS:-ClinEpiDB/%DB_BUILD%/eda-studies-binary;MicrobiomeDB/%DB_BUILD%/eda-studies-binary;*/%DB_BUILD%/*/eda-studies-binary}

      # LDAP values to look up DBs
      LDAP_SERVER: ${LDAP_SERVER}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN}

      # Application Database
      APP_DB_TNS_NAME: ${APP_DB_TNS_NAME}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASS: ${APP_DB_PASS}
      APP_DB_SCHEMA: ${APP_DB_SCHEMA:-eda.}

      # Account Database
      ACCT_DB_TNS_NAME: ${ACCT_DB_TNS_NAME}
      ACCT_DB_USER: ${ACCT_DB_USER}
      ACCT_DB_PASS: ${ACCT_DB_PASS}

      # User Database
      USER_DB_TNS_NAME: ${USER_DB_TNS_NAME}
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASS: ${USER_DB_PASS}
      USER_DB_SCHEMA: ${USER_DB_SCHEMA:-userlogins5}

      # Auth Secret (needed along with user/acct DBs for auth)
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}

    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${SUBSETTING_WATCHTOWER:-false}"
    - "traefik.http.services.${TRAEFIK_SUBSETTING_ROUTER:-edasubsetting-dev}.loadbalancer.server.port=${SUBSETTING_SERVER_PORT:-8080}"
    - "traefik.http.routers.${TRAEFIK_SUBSETTING_ROUTER:-edasubsetting-dev}.rule=Host(`${TRAEFIK_DATA_HOST:-edadata-dev.local.apidb.org}`) && PathPrefix(`/studies`,`/clear-metadata-cache`)"
    - "traefik.http.routers.${TRAEFIK_SUBSETTING_ROUTER:-edasubsetting-dev}.tls=true"
    - "traefik.http.routers.${TRAEFIK_SUBSETTING_ROUTER:-edasubsetting-dev}.entrypoints=${TRAEFIK_ENTRYPOINTS:-local}"
    - "traefik.docker.network=traefik"

  merging:
    image: veupathdb/eda-merging:${MERGING_TAG:-latest}
    networks:
      internal:
        aliases:
          - merging-internal
      monitoring-ext:
    environment:
      # port providing the service
      SERVER_PORT: ${MERGING_SERVER_PORT:-8080}

      # URLs of required services
      SUBSETTING_SERVICE_URL: ${SUBSETTING_SERVICE_URL:-http://subsetting-internal}:${SUBSETTING_SERVER_PORT:-8080}

    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${MERGING_WATCHTOWER:-false}"

  data:
    image: veupathdb/eda-data:${DATA_TAG:-latest}
    networks:
      internal:
        aliases:
          - data-internal
      traefik:
      monitoring-ext:
    environment:
      # port providing the service
      SERVER_PORT: ${DATA_SERVER_PORT:-8080}

      # URLs of required services
      SUBSETTING_SERVICE_URL: ${SUBSETTING_SERVICE_URL:-http://subsetting-internal}:${SUBSETTING_SERVER_PORT:-8080}
      MERGING_SERVICE_URL: ${MERGING_SERVICE_URL:-http://merging-internal}:${MERGING_SERVER_PORT:-8080}
      RSERVE_URL: ${RSERVE_URL:-http://rserve-internal:6311}
      DATASET_ACCESS_SERVICE_URL: ${DATASET_ACCESS_SERVICE_URL:-http://dataset-access-internal}:${DATASET_ACCESS_SERVER_PORT:-8080}

      # LDAP values to look up DBs
      LDAP_SERVER: ${LDAP_SERVER}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN}

      # Account Database
      ACCT_DB_TNS_NAME: ${ACCT_DB_TNS_NAME}
      ACCT_DB_USER: ${ACCT_DB_USER}
      ACCT_DB_PASS: ${ACCT_DB_PASS}

      # User Database
      USER_DB_TNS_NAME: ${USER_DB_TNS_NAME}
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASS: ${USER_DB_PASS}
      USER_DB_SCHEMA: ${USER_DB_SCHEMA:-userlogins5}

      # Auth Secret (needed along with user/acct DBs for auth)
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}

    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${DATA_WATCHTOWER:-false}"
    - "traefik.http.services.${TRAEFIK_DATA_ROUTER:-edadata-dev}.loadbalancer.server.port=${DATA_SERVER_PORT:-8080}"
    - "traefik.http.routers.${TRAEFIK_DATA_ROUTER:-edadata-dev}.rule=Host(`${TRAEFIK_DATA_HOST:-edadata-dev.local.apidb.org}`)"
    - "traefik.http.routers.${TRAEFIK_DATA_ROUTER:-edadata-dev}.tls=true"
    - "traefik.http.routers.${TRAEFIK_DATA_ROUTER:-edadata-dev}.entrypoints=${TRAEFIK_ENTRYPOINTS:-local}"
    - "traefik.docker.network=traefik"

  rserve:
    image: veupathdb/rserve:${RSERVE_TAG:-latest}
    networks:
      internal:
        aliases:
          - rserve-internal
    labels:
    - "com.centurylinklabs.watchtower.enable=${RSERVE_WATCHTOWER:-false}"

  user:
    image: veupathdb/eda-user:${USER_TAG:-latest}
    networks:
      internal:
        aliases:
          - user-internal
      external:
      monitoring-ext:
      traefik:
    environment:
      # port providing the service
      SERVER_PORT: ${USER_SERVER_PORT:-8080}

      # LDAP values to look up DBs
      LDAP_SERVER: ${LDAP_SERVER}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN}

      # Account Database
      ACCT_DB_TNS_NAME: ${ACCT_DB_TNS_NAME}
      ACCT_DB_USER: ${ACCT_DB_USER}
      ACCT_DB_PASS: ${ACCT_DB_PASS}

      # User Database
      USER_DB_TNS_NAME: ${USER_DB_TNS_NAME}
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASS: ${USER_DB_PASS}
      USER_DB_SCHEMA: ${USER_DB_SCHEMA:-userlogins5}

      # Auth Secret (needed along with user/acct DBs for auth)
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}

      # Project-specific properties for user schema
      PROJECT_SPECIFIC_PROP_CE_PROJECT_ID: ClinEpiDB
      PROJECT_SPECIFIC_PROP_CE_USER_SCHEMA: edauserce

      PROJECT_SPECIFIC_PROP_ACE_PROJECT_ID: AllClinEpiDB
      PROJECT_SPECIFIC_PROP_ACE_USER_SCHEMA: edauserce

      PROJECT_SPECIFIC_PROP_MB_PROJECT_ID: MicrobiomeDB
      PROJECT_SPECIFIC_PROP_MB_USER_SCHEMA: edausermb

      PROJECT_SPECIFIC_PROP_VB_PROJECT_ID: VectorBase
      PROJECT_SPECIFIC_PROP_VB_USER_SCHEMA: edauservb

    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${USER_WATCHTOWER:-false}"
    - "traefik.http.services.${TRAEFIK_USER_ROUTER:-edauser-dev}.loadbalancer.server.port=${USER_SERVER_PORT:-8080}"
    - "traefik.http.routers.${TRAEFIK_USER_ROUTER:-edauser-dev}.rule=Host(`${TRAEFIK_DATA_HOST:-edadata-dev.local.apidb.org}`) && PathPrefix(`/users/`,`/public/`,`/import-analysis`)"
    - "traefik.http.routers.${TRAEFIK_USER_ROUTER:-edauser-dev}.tls=true"
    - "traefik.http.routers.${TRAEFIK_USER_ROUTER:-edauser-dev}.entrypoints=${TRAEFIK_ENTRYPOINTS:-local}"
    - "traefik.docker.network=traefik"

  dataset-access:
    image: veupathdb/dataset-access-service:${DAS_TAG:-latest}
    networks:
      internal:
        aliases:
          - dataset-access-internal
      external:
      monitoring-ext:
      traefik:
    environment:
      # port providing the service
      SERVER_PORT: ${DATASET_ACCESS_SERVER_PORT:-8080}

      # LDAP values to look up DBs
      LDAP_SERVER: ${LDAP_SERVER}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN}

      # Application Database
      APP_DB_TNS_NAME: ${APP_DB_TNS_NAME}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASS: ${APP_DB_PASS}
      APP_DB_POOL_SIZE: 20

      # Account Database
      ACCT_DB_TNS_NAME: ${ACCT_DB_TNS_NAME}
      ACCT_DB_USER: ${ACCT_DB_USER}
      ACCT_DB_PASS: ${ACCT_DB_PASS}
      ACCT_DB_POOL_SIZE: 20

      # User Database
      USER_DB_TNS_NAME: ${USER_DB_TNS_NAME}
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASS: ${USER_DB_PASS}
      USER_DB_SCHEMA: ${USER_DB_SCHEMA:-userlogins5}

      # Auth Secret (needed along with user/acct DBs for auth)
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}

      # Email Config
      SMTP_HOST: ${SMTP_HOST?required}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL?required}
      EMAIL_DEBUG: !!str false

      # Web Client URLs
      SITE_URL: ${SITE_URL}                     # e.g. https://clinepidb.org/ce
      REGISTRATION_PATH: /app/user/registration # unused for now
      APPLICATION_PATH: /app/study-access       # unused for now

    labels:
    - "prometheus-scrape.enabled=true"
    - "com.centurylinklabs.watchtower.enable=${DAS_WATCHTOWER:-false}"
    - "traefik.http.services.${TRAEFIK_DAS_ROUTER:-edadas-dev}.loadbalancer.server.port=${DATASET_ACCESS_SERVER_PORT:-8080}"
    - "traefik.http.routers.${TRAEFIK_DAS_ROUTER:-edadas-dev}.rule=Host(`${TRAEFIK_DATA_HOST:-edadata-dev.local.apidb.org}`) && PathPrefix(`/staff`,`/dataset-providers`,`/dataset-end-users`,`/permissions`,`/history`)"
    - "traefik.http.routers.${TRAEFIK_DAS_ROUTER:-edadas-dev}.tls=true"
    - "traefik.http.routers.${TRAEFIK_DAS_ROUTER:-edadas-dev}.entrypoints=${TRAEFIK_ENTRYPOINTS:-local}"
    - "traefik.docker.network=traefik"

  dataset-download:
    image: veupathdb/dataset-download-service:${DDS_TAG:-latest}
    networks:
      internal:
        aliases:
          - dataset-download-internal
      external:
      monitoring-ext:
      traefik:
    volumes:
      - type: bind
        source: ${DOWNLOAD_FILES_DIR:-/var/www/Common/apiSiteFilesMirror/downloadSite}
        target: /downloadFiles
        read_only: true
    environment:
      # port providing the service
      SERVER_PORT: ${DATASET_DOWNLOAD_SERVER_PORT:-8080}

      # URLs of required services
      DATASET_ACCESS_SERVICE_URL: ${DATASET_ACCESS_SERVICE_URL:-http://dataset-access-internal}:${DATASET_ACCESS_SERVER_PORT:-8080}

      # LDAP values to look up DBs
      LDAP_SERVER: ${LDAP_SERVER}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN}

      # Account Database
      ACCT_DB_TNS_NAME: ${ACCT_DB_TNS_NAME}
      ACCT_DB_USER: ${ACCT_DB_USER}
      ACCT_DB_PASS: ${ACCT_DB_PASS}
      ACCT_DB_POOL_SIZE: 20

      # User Database
      USER_DB_TNS_NAME: ${USER_DB_TNS_NAME}
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASS: ${USER_DB_PASS}
      USER_DB_SCHEMA: ${USER_DB_SCHEMA:-userlogins5}

      # Auth Secret (needed along with user/acct DBs for auth)
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}

      # Parent directory for raw download files
      DOWNLOAD_FILES_MOUNT_PATH: ${DOWNLOAD_FILES_MOUNT_PATH:-/downloadFiles}

      # Project-specific properties for raw files parent directory
      PROJECT_SPECIFIC_PROP_CE_PROJECT_ID: ClinEpiDB
      PROJECT_SPECIFIC_PROP_CE_RAW_FILES_DIR: ClinEpiDB

      PROJECT_SPECIFIC_PROP_ACE_PROJECT_ID: AllClinEpiDB
      PROJECT_SPECIFIC_PROP_ACE_RAW_FILES_DIR: ClinEpiDB

      PROJECT_SPECIFIC_PROP_MB_PROJECT_ID: MicrobiomeDB
      PROJECT_SPECIFIC_PROP_MB_RAW_FILES_DIR: MicrobiomeDB

    labels:
    - "prometheus-scrape.enabled=true"
    - "com.centurylinklabs.watchtower.enable=${DDS_WATCHTOWER:-false}"
    - "traefik.http.services.${TRAEFIK_DDS_ROUTER:-edadds-dev}.loadbalancer.server.port=${DATASET_DOWNLOAD_SERVER_PORT:-8080}"
    - "traefik.http.routers.${TRAEFIK_DDS_ROUTER:-edadds-dev}.rule=Host(`${TRAEFIK_DATA_HOST:-edadata-dev.local.apidb.org}`) && PathPrefix(`/download`)"
    - "traefik.http.routers.${TRAEFIK_DDS_ROUTER:-edadds-dev}.tls=true"
    - "traefik.http.routers.${TRAEFIK_DDS_ROUTER:-edadds-dev}.entrypoints=${TRAEFIK_ENTRYPOINTS:-local}"
    - "traefik.docker.network=traefik"

networks:
  # external network used for containers that need to reach outside
  external:
  traefik:
    external: true
  internal:
    internal: true
  monitoring-ext:
    external: true

