= Example Containerized JaxRS Service
:toc: left
:source-highlighter: pygments
:icons: font
// Github specifics
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
Elizabeth Paige Harper <epharper@upenn.edu>
v1.0.0

== Running the Example

=== Locally

==== Prerequisites

* Maven
* NodeJS/NPM

==== Setup & Run

Environment/dependency setup for local development can be done via the command
`make install-dev-env`.  This will install the dependencies required to build the
project.

After the environment has been set up, the project can be built, tested, and
packaged using `make jar`.

Starting the server can be done by running `java -jar build/lib/service.jar`.

=== In Docker

==== Prerequisites

* Docker

==== Setup & Run

The project container can be built using `make docker`.  The first build
of the container will take several minutes.

Running the built container can be done with `docker run --rm demo-service`.


//------------------------------------------------------------------------------


== Development

To use this project as a template for the development of a new service, use the
"Use this template" button above to create a new project based off of this repo.

=== Quick Start

. Clone your new project and cd into the cloned directory
. Run `make cleanup-example install-dev-env`
. Edit `service.properties` with your service's details.
. Run `make fix-path` to
. Edit `api.raml` with your API design
. Create any necessary types in `docs/schema`
. Run `make gen-jaxrs`
. Implement the generated service interfaces.
. Register your

=== Environment

Once your new project has been cloned, the development prerequisites can be
installed using `make install-dev-env`.  This will install and build the following
packages:

* NPM
** https://github.com/davidkelley/json-dereference-cli[json-dereference-cli]
** https://github.com/raml2html/raml2html[raml2html]
** https://github.com/raml-org/ramldt2jsonschema[ramldt2jsonschema]
* Maven
** https://github.com/mulesoft-labs/raml-for-jax-rs[raml-to-jaxrs]
** https://github.com/VEuPathDB/FgpUtil[FgpUtil]

After (or during) installing the prerequisites, you may run
`make cleanup-example` to remove the Java classes generated for the demo.

=== Configuration

Configuration for the build is primarily done through the `service.properties`
file.  Here you can configure the project's name, version, container name,
Java package structure, etc...

If additional dependencies are required, they will be added to the
`build.gradle.kts` file.  For information about adding gradle dependencies see
the https://docs.gradle.org/current/userguide/declaring_dependencies.html[Gradle
docs].

=== API definition

The service api is defined in 2 places initially: the `api.raml` file and the
type definition files under the directory `docs/schema`.  These files must be
valid Raml 1.0 Librariesfootnote:[Modular Raml Guide:https://medium.com/raml-api/raml-101-libraries-and-datatypes-fragments-1889b2e82c27]footnote:[Modular Raml Guide: https://www.baeldung.com/modular-raml-includes-overlays-libraries-extensions].

==== `api.raml`

In the `api.raml` file, there is an include near the top of the file that
declares the Raml file "uses" `docs/raml/library.raml`.  This file is generated
from the schema files and should not be edited directly.

.api.raml
[source, yaml, linenums, start=5]
----
uses:
  lib: docs/raml/library.raml
----

Referencing types defined in the schema directory can be done by using the `lib`
package name.

==== Type Schema

Each raml library file under `docs/schema` should define a root `types` object
defining the types used by the API.  The name of a types defined under the
`types` object will be the name of the generated Java class based on that type
definition.

.Type definition
====
.Example Schema
[source, yaml]
----
#%RAML 1.0 Library
types:
  MyType:
    properties:
      foo: string
----

.Resulting Java Interface
[source, java]
----
package org.veupathdb.service.demo.generated.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@JsonDeserialize(
    as = HealthResponseImpl.class
)
public interface MyType {
  @JsonProperty("foo")
  StatusType getFoo();

  @JsonProperty("foo")
  void setFoo(String foo);
}
----

.Resulting Java Class
[source, java]
----
package org.veupathdb.service.demo.generated.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "foo",
})
public class HealthResponseImpl implements HealthResponse {
  @JsonProperty("foo")
  private String foo;

  @JsonProperty("foo")
  public String getFoo() {
    return this.foo;
  }

  @JsonProperty("foo")
  public void setFoo(String foo) {
    this.foo = foo;
  }
}
----

====

=== Generating A Service

Once your API is layed out, you can begin development of Java code by running
`make gen-jaxrs`.  This will create a skeleton of the API in the `generated`
source package located under the `app.package` packaged defined in
`service.properties`.

The generated interfaces and types have the basic necessary annotations for use
by both Jackson and Jersey.

Once you have implemented the interfaces defined under
`\{source-package}.generated.resources` they must be registered in the
`\{source-package}.Resources` class.

=== Run Your Service

Running your service locally can be done by following the same steps as defined
above in the <<Running the Example>> section:

. Run `make build-jar`
. Run `java -jar build/lib/service.jar`

Running in Docker can be done by:

. Run `make build-docker`
. Run `docker run <your-image-name>`

== Other Information

=== Make Targets

`compile`:: Compiles the Java code currently in the `src/` directory.  Does not
perform any code/doc generation.

`gen-compile`:: Runs code generation then compiles.

`test`:: Runs unit tests against the code currently in the `src` directory.

`build-jar`:: Compiles and packages a self-contained runnable jar from the
project.  This _will_ perform code and doc generation.

`build-docker`:: Builds a runnable docker image from the project.  This _will_
perform code and doc generation (in the container).

`local-dev`:: Sets up the local environment/workspace for local development.
+
* Downloads and builds raml-to-jaxrs
* Downloads and builds FgpUtil
* Installs the required NPM packages

`prep-env`:: Ensures the required binaries are available on the `$PATH` and
installs the required NPM packages globally.

`build-r2j`:: Builds the raml-to-jaxrs jar.

`gen-jaxrs`:: Performs Java code generation from the Raml spec.

`gen-docs`:: Performs API doc generation from the Raml spec.

`docs/raml/library.raml`:: Converts the Json schema files to a Raml library.

`install-fgputil`:: Downloads and builds FgpUtil, placing it in a "vendor"
directory in the workspace from which Gradle can compile against it.

`cleanup-example`:: Removes the code generated from the example Raml spec.

`gradle-ping`:: Verifies that Gradle is downloaded and ready for use.
