#%RAML 1.0 Library

types:

  StandaloneMapMarkersPostRequest:
    type: VisualizationRequestBase
    properties:
      config: StandaloneMapMarkerSpec

  StandaloneMapMarkerSpec:
    additionalProperties: false
    properties:
      outputEntityId: 
        type: string
      geoAggregateVariable:
        type: VariableSpec
      longitudeVariable:
        type: VariableSpec
      latitudeVariable:
        type: VariableSpec
      overlayVariable?:
        type: VariableSpec
      overlayValues?:
        type: BinRange[] # categoricals can just ignore bin start and end
      # if we choose to support things like means and medians for cont vars this may need to be a custom enum
      valueSpec:
        type: ValueSpec
      viewport:
        type: GeolocationViewport

  StandaloneMapMarkersPostResponse:
    additionalProperties: false
    properties:
      mapElements: StandaloneMapElementInfo[]

  # TODO remove once quantile endpoint is merged.
  BinRange:
    additionalProperties: false
    properties:
      binStart?: string # number | date
      binEnd?: string # number | date
      binLabel: string

  BinRangeWithValue:
    additionalProperties: false
    type: BinRange
    properties:
      value: number

  StandaloneMapElementInfo:
    additionalProperties: false
    properties:
      geoAggregateValue:
        type: string
      entityCount:
        type: number
      overlayValues:
        type: BinRangeWithValue[]
      avgLat:
        type: number
      avgLon:
        type: number
      minLat:
        type: number
      minLon:
        type: number
      maxLat:
        type: number
      maxLon:
        type: number
