#%RAML 1.0 Library

types:

  FloatingHistogramPostRequest:
    type: VisualizationRequestBase
    properties:
      config: FloatingHistogramSpec

  FloatingHistogramSpec:
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      xAxisVariable:
        type: VariableSpec
      barMode:
        type: string
        enum: ['overlay', 'stack']
      valueSpec: 
        type: ValueSpec
      overlayVariable?: 
        type: VariableSpec
        required: false
      overlayValues?:
        type: NumericBinRange[] # categoricals can just ignore bin start and end
      binSpec:
        type: BinSpec
      viewport:
        type: NumericViewport
        required: false

  FloatingHistogram:
    additionalProperties: false
    properties:
      data:
        type: HistogramData[]
      variables: VariableMapping[]

  FloatingHistogramPostResponse:
    additionalProperties: false
    properties:
      histogram:
        type: FloatingHistogram
