#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  FloatingBarplotPostRequest:
    type: VisualizationRequestBase
    properties:
      config: FloatingBarplotSpec
  
  # do we need a BaseBarPlot type or something? 
  # i think that wouldnt have an overlay, so wed need this anyway...
  # might help w writing the plugins ??

  # TODO the float chart specs need to gain overlayValues like the markers plugin has
  FloatingBarplotSpec:
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      barMode:
        type: string
        enum: ['group', 'stack']
      valueSpec:
        type: ValueSpec
      xAxisVariable: 
        type: VariableSpec
      overlayVariable: 
        type: VariableSpec
        required: false
      overlayValues?:
        type: BinRange[] # categoricals can just ignore bin start and end

  FloatingBarplot:
    additionalProperties: false
    properties:
      data:
        type: BarplotData[]
      variables: VariableMapping[]

  FloatingBarplotPostResponse:
    additionalProperties: false
    properties:
      barplot:
        type: FloatingBarplot
