#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  FloatingMosaicPostRequest:
    type: VisualizationRequestBase
    properties:
      config: FloatingMosaicSpec

  FloatingMosaicSpec:
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      xAxisVariable:
        type: VariableSpec
      yAxisVariable:
        type: VariableSpec

  FlatingMosaic:
    additionalProperties: false
    properties:
      data:
        type: MosaicData[]
      variables: VariableMapping[]

  FloatingContTablePostResponse:
    additionalProperties: false
    properties:
      mosaic:
        type: FloatingMosaic
      statsTable:
        type: TwoByTwoStatsTable[]
        required: false