#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  FloatingBoxplotPostRequest:
    type: DataPluginRequestBase
    properties:
      config: FloatingBoxplotSpec

  # think this always gives outliers and means, saves some user configuration?
  FloatingBoxplotSpec:
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      xAxisVariable: 
        type: VariableSpec
      yAxisVariable: 
        type: VariableSpec
      overlayVariable?: 
        type: VariableSpec
        required: false
      overlayValues?:
        type: BinRange[] # categoricals can just ignore bin start and end
      maxAllowedDataPoints:
        type: integer
        format: int64
        required: false
      
  FloatingBoxplot:
    additionalProperties: false
    properties:
      data:
        type: BoxplotData[]
      variables: VariableMapping[]

  FloatingBoxplotPostResponse:
    additionalProperties: false
    properties:
      boxplot:
        type: FloatingBoxplot