package org.veupathdb.service.eda.merging.plugins;

import org.veupathdb.service.eda.merging.core.derivedvars.DerivedVariableFactory;
import org.veupathdb.service.eda.merging.core.derivedvars.Transform;
import org.veupathdb.service.eda.merging.plugins.transforms.*;

import static org.veupathdb.service.eda.merging.core.derivedvars.DerivedVariableFactory.pluginsOf;

/**
 * Provides the definitive list of transform derived variables which may be generated by this service
 */
public class Transforms {
  public static DerivedVariableFactory.PluginMap<Transform> getPlugins() {
    return pluginsOf(Transform.class,
        // available transforms
        Concatenation.class,
        BodyMassIndex.class,
        CategoricalRecoding.class,
        ContinuousNumericToOrdinal.class,
        AdvancedSubset.class,
        EcmaScriptExpressionEval.class,
        RelativeObservationMinTimeInterval.class,
        UnitConversion.class
    );
  }
}
