#%RAML 1.0 Library

types:

  CorrelationAssayAssayBipartitenetworkPostRequest:
    type: DataPluginRequestBase
    properties:
      computeConfig: Correlation2Collections
      config: CorrelationNetworkSpec

