#%RAML 1.0 Library

types:

# Temporary until the backend is really ready
  CorrelationAssayMetadataBipartitenetworkPostRequest:
    type: DataPluginRequestBase
    properties:
      computeConfig: CorrelationComputeConfig
      config: CorrelationAssayMetadataBipartitenetworkSpec

  CorrelationAssayMetadataStatsResponse:
    additionalProperties: false
    properties:
      statistics: CorrelationPoint[]
      data1Metadata: string
      data2Metadata: string

  CorrelationAssayMetadataBipartitenetworkSpec:
    additionalProperties: false
    properties:
      significanceThreshold:
        type: number
        required: false
      correlationCoefThreshold:
        type: number
        required: false

  # CorrelationStatsResponse:
  #   type: CorrelationPoint[]

  CorrelationPoint:
    properties: 
      data1: string
      data2: string
      correlationCoef: 
        type: string
        required: false
      pValue: 
        type: string
        required: false
      adjustedPValue:
        type: string
        required: false

  CorrelationComputeConfig:
    properties:
      collectionVariable1: 
        type: CollectionSpec
        required: false
      collectionVariable2:
        type: CollectionSpec
        required: false
      correlationMethod: CorrelationMethod

  CorrelationMethod:
    type: string
    enum: ['spearman','pearson']