#%RAML 1.0 Library

types:

# Temporary until the backend is really ready
  CorrelationAssayMetadataBipartitenetworkPostRequest:
    type: DataPluginRequestBase
    properties:
      computeConfig: CorrelationComputeConfig
      config: CorrelationAssayMetadataBipartitenetworkSpec

  CorrelationAssayMetadataStatsResponse:
    additionalProperties: false
    properties:
      statistics: CorrelationPoint[]
      data1Metadata: string
      data2Metadata: string

  CorrelationAssayMetadataBipartitenetworkSpec:
    additionalProperties: false
    properties:
      significanceThreshold:
        type: number
        required: false
      correlationCoefThreshold:
        type: number
        required: false