#%RAML 1.0 Library

types:

# Temporary until the backend is really ready
  CorrelationAssayMetadataBipartitenetworkPostRequest:
    type: DataPluginRequestBase
    properties:
      computeConfig: EmptyDataPluginSpec
      config: EmptyDataPluginSpec

  CorrelationAssayMetadataStatsResponse:
    type: DifferentialAbundanceStatsResponse
