#%RAML 1.0 Library

types:
  ErrorResponse:
    additionalProperties: false
    discriminator: status
    properties:
      status: string
      message: string

  BadRequestError:
    displayName: 400 Response
    type: ErrorResponse
    discriminatorValue: bad-request

  UnauthorizedError:
    displayName: 401 Response
    type: ErrorResponse
    discriminatorValue: unauthorized

  InvalidInputError:
    displayName: 422 Response
    type: ErrorResponse
    discriminatorValue: invalid-input
    properties:
      errors:
        additionalProperties: false
        properties:
          general:
            type: array
            items: string
          byKey:
            properties:
              //: string

  ServerError:
    displayName: 500 Response
    type: ErrorResponse
    discriminatorValue: server-error
    properties:
      requestId: string
