#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  BarplotPostRequest:
    type: DataPluginRequestBase
    properties:
      config: BarplotSpec
  
  BarplotSpec:
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      showMissingness:
        type: ShowMissingnessNoAxes
        required: false
      barMode:
        type: string
        enum: ['group', 'stack']
      valueSpec:
        type: ValueSpec
      xAxisVariable: 
        type: VariableSpec
      overlayVariable: 
        type: VariableSpec
        required: false
      facetVariable: 
        type: VariableSpec[]
        maxItems: 2
        required: false

  Barplot:
    additionalProperties: false
    properties:
      data:
        type: BarplotData[]
      config:
        type: PlotConfig

  BarplotPostResponse:
    additionalProperties: false
    properties:
      barplot:
        type: Barplot
      sampleSizeTable:
        type: SampleSizeTable[]
      completeCasesTable:
        type: VariableCompleteCases[]
