#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  PieplotPostRequest:
    type: VisualizationRequestBase
    properties:
      config: PieplotSpec
  
  # were making overlay required, since this plot has no formal axes in the schema
  PieplotSpec:
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      showMissingness:
        type: string
        enum: ['TRUE', 'FALSE']
        required: false
      overlayVariable: 
        type: VariableSpec
      facetVariable: 
        type: VariableSpec[]
        maxItems: 2
        required: false
      valueSpec: 
        type: ValueSpec

  PieplotConfig:
    type: PlotConfig
    properties:
      rankedOverlayValues:
        type: string[]
        minItems: 1
        maxItems: 8

  Pieplot:
    additionalProperties: false
    properties:
      data:
        type: PieplotData[]
      config:
        type: PieplotConfig

  PieplotPostResponse:
    additionalProperties: false
    properties:
      Pieplot:
        type: Pieplot
      sampleSizeTable:
        type: SampleSizeTable[]
      completeCasesTable:
        type: VariableCompleteCases[]