#%RAML 1.0 Library

types:

  DateHistogramNumBinsPostRequest:
    type: HistogramPostRequest
    properties:
      config: DateHistogramNumBinsSpec

  DateHistogramNumBinsSpec:
    type: HistogramSpec
    properties:
      numBins:
        type: number
        required: false
      viewportMin:
        type: string
        required: false
      viewportMax:
        type: string
        required: false
        
  DateHistogramNumBinsConfig:
    type: HistogramResponseConfig
    properties:
      numBins: 
        type: number
        
  DateHistogramNumBinsPostResponse:
    additionalProperties: false
    properties:
      data:
        type: HistogramResponseData[]
      config:
        type: DateHistogramNumBinsConfig