#%RAML 1.0 Library

types:

  MapPostRequest:
    type: VisualizationRequestBase
    properties:
      config: MapSpec

  MapSpec:
    additionalProperties: false
    properties:
      outputEntityId: 
        type: string
      geoAggregateVariable:
        type: VariableSpec
      longitudeVariable:
        type: VariableSpec
      latitudeVariable:
        type: VariableSpec

  MapPostResponse:
    additionalProperties: false
    properties:
      mapElements: MapElementInfo[]

  MapElementInfo:
    additionalProperties: false
    properties:
      geoAggregateValue:
        type: string
      entityCount:
        type: number
      avgLat:
        type: number
      avgLon:
        type: number
      minLat:
        type: number
      minLon:
        type: number
      maxLat:
        type: number
      maxLon:
        type: number
