#%RAML 1.0 Library

types:

  NumericHistogramNumBinsPostRequest:
    type: HistogramPostRequest
    properties:
      config: NumericHistogramNumBinsSpec

  NumericHistogramNumBinsSpec:
    type: HistogramSpec
    properties:
      numBins:
        type: number
        required: false
      viewportMin:
        type: number
        required: false
      viewportMax:
        type: number
        required: false
        
  NumericHistogramNumBinsConfig:
    type: HistogramResponseConfig
    properties:
      numBins: 
        type: number
        
  NumericHistogramNumBinsPostResponse:
    additionalProperties: false
    properties:
      data:
        type: HistogramResponseData[]
      config:
        type: NumericHistogramNumBinsConfig