#%RAML 1.0 Library

types:

  HistogramPostRequest:
    type: VisualizationRequestBase
    properties:
      config: HistogramSpec

  HistogramSpec:
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      showMissingness:
        type: ShowMissingnessNoAxes
        required: false
      xAxisVariable:
        type: VariableSpec
      barMode:
        type: string
        enum: ['overlay', 'stack']
      valueSpec: 
        type: ValueSpec
      overlayVariable: 
        type: VariableSpec
        required: false
      facetVariable: 
        type: VariableSpec[]
        maxItems: 2
        required: false
      binSpec:
        type: BinSpec
      viewport:
        type: XAxisViewport
        required: false
        
  HistogramSummary:
    properties:
      min:
        type: string
      q1:
        type: string
      median:
        type: string
      mean:
        type: string
      q3:
        type: string
      max:
        type: string  
        
  HistogramConfig:
    type: PlotConfig
    properties:
      binSlider:
        type: BinSlider
      xVariableDetails:
        type: VariableSpec    
      binSpec:
        type: BinSpec
      summary:
        type: HistogramSummary
      viewport:
        type: XAxisViewport

  Histogram:
    additionalProperties: false
    properties:
      data:
        type: HistogramData[]
      config:
        type: HistogramConfig

  HistogramPostResponse:
    additionalProperties: false
    properties:
      histogram:
        type: Histogram
      sampleSizeTable:
        type: SampleSizeTable[]
      completeCasesTable:
        type: VariableCompleteCases[]