#%RAML 1.0 Library

types:

  NumericHistogramBinWidthPostRequest:
    type: HistogramPostRequest
    properties:
      config: NumericHistogramBinWidthSpec

  NumericHistogramBinWidthSpec:
    type: HistogramSpec
    properties:
      binWidth:
        type: number
        required: false
      viewportMin:
        type: number
        required: false
      viewportMax:
        type: number
        required: false
  
  NumericHistogramBinWidthConfig:
    type: HistogramResponseConfig
    properties:
      binWidth: 
        type: number
        
  NumericHistogramBinWidthPostResponse:
    additionalProperties: false
    properties:
      data:
        type: HistogramResponseData[]
      config:
        type: NumericHistogramBinWidthConfig