#%RAML 1.0 Library

types:

  NumericHistogramNumBinsPostRequest:
    type: HistogramPostRequest
    properties:
      config: NumericHistogramNumBinsSpec 

  NumericHistogramNumBinsSpec:
    type: HistogramSpec
    properties:
      numBins:
        type: number
        required: false
      viewportMin:
        type: number
        required: false
      viewportMax:
        type: number
        required: false
  
  NumericHistogramNumBinsSummary:
    properties:
      min:
        type: number
      q1:
        type: number
      median:
        type: number
      mean:
        type: number
      q3:
        type: number
      max:
        type: number
                
  NumericHistogramNumBinsViewportResponse:
    properties:
      xMin:
        type: number
      xMax:
        type: number
        
  NumericHistogramNumBinsConfig:
    type: HistogramResponseConfig
    properties:
      numBins: 
        type: number
      summary:
        type: NumericHistogramNumBinsSummary
      viewport:
        type: NumericHistogramNumBinsViewportResponse
        
  NumericHistogramNumBinsPostResponse:
    additionalProperties: false
    properties:
      data:
        type: HistogramResponseData[]
      config:
        type: NumericHistogramNumBinsConfig