#%RAML 1.0 Library

types:

  DateHistogramNumBinsPostRequest:
    type: HistogramPostRequest
    properties:
      config: DateHistogramNumBinsSpec

  DateHistogramNumBinsSpec:
    type: HistogramSpec
    properties:
      numBins:
        type: number
        required: false
      viewportMin:
        type: string
        required: false
      viewportMax:
        type: string
        required: false
        
  DateHistogramNumBinsSummary:
    properties:
      min:
        type: string
      q1:
        type: string
      median:
        type: string
      mean:
        type: string
      q3:
        type: string
      max:
        type: string
                
  DateHistogramNumBinsViewportResponse:
    properties:
      xMin:
        type: string
      xMax:
        type: string
        
  DateHistogramNumBinsConfig:
    type: HistogramResponseConfig
    properties:
      numBins: 
        type: string
      summary:
        type: DateHistogramNumBinsSummary
      viewport:
        type: DateHistogramNumBinsViewportResponse
        
  DateHistogramNumBinsPostResponse:
    additionalProperties: false
    properties:
      data:
        type: HistogramResponseData[]
      config:
        type: DateHistogramNumBinsConfig