#%RAML 1.0 Library

types:

  NumericHistogramBinWidthPostRequest:
    type: HistogramPostRequest
    properties:
      config: NumericHistogramBinWidthSpec

  NumericHistogramBinWidthSpec:
    type: HistogramSpec
    properties:
      binWidth:
        type: number
        required: false
      viewportMin:
        type: number
        required: false
      viewportMax:
        type: number
        required: false
  
  NumericHistogramBinWidthSummary:
    properties:
      min:
        type: number
      q1:
        type: number
      median:
        type: number
      mean:
        type: number
      q3:
        type: number
      max:
        type: number
                
  NumericHistogramBinWidthViewportResponse:
    properties:
      xMin:
        type: number
      xMax:
        type: number
        
  NumericHistogramBinWidthConfig:
    type: HistogramResponseConfig
    properties:
      binWidth: 
        type: number
      summary:
        type: NumericHistogramBinWidthSummary
      viewport:
        type: NumericHistogramBinWidthViewportResponse
        
  NumericHistogramBinWidthPostResponse:
    additionalProperties: false
    properties:
      data:
        type: HistogramResponseData[]
      config:
        type: NumericHistogramBinWidthConfig