#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  BoxplotPostRequest:
    type: VisualizationRequestBase
    properties:
      config: BoxplotSpec

  BoxplotSpec:
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      showMissingness:
        type: ShowMissingnessNoAxes
        required: false
      points:
        type: string
        enum: ['outliers', 'all']
      mean:
        type: string
        enum: ['TRUE', 'FALSE']
      computeStats:
        type: string
        enum: ['TRUE', 'FALSE']
      xAxisVariable: 
        type: VariableSpec
      yAxisVariable: 
        type: VariableSpec
      overlayVariable: 
        type: VariableSpec
        required: false
      facetVariable: 
        type: VariableSpec[]
        maxItems: 2
        required: false
      maxAllowedDataPoints:
        type: integer
        required: false
      

  BoxplotConfig:
    type: PlotConfig
    properties:
      xVariableDetails:
        type: VariableSpec
      yVariableDetails:
        type: VariableSpec

  Boxplot:
    additionalProperties: false
    properties:
      data:
        type: BoxplotData[]
      config:
        type: BoxplotConfig

  BoxplotPostResponse:
    additionalProperties: false
    properties:
      boxplot:
        type: Boxplot
      sampleSizeTable:
        type: SampleSizeTable[]
      completeCasesTable:
        type: VariableCompleteCases[]
      statsTable:
        type: BoxplotStatsTable[]
        required: false