#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  BarplotPostRequest:
    type: VisualizationRequestBase
    properties:
      config: BarplotSpec

  BarplotSpec:
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      valueSpec:
        type: string
        enum: ['identity', 'count']
      xAxisVariable: 
        type: VariableSpec
      overlayVariable: 
        type: VariableSpec
        required: false
      facetVariable: 
        type: VariableSpec[]
        maxItems: 2
        required: false

  BarplotResponseConfig:
    type: VisualizationConfig
    properties:
      xVariableDetails:
        type: VariableSpec

  BarplotPostResponse:
    additionalProperties: false
    properties:
      data:
        type: BarplotResponseData[]
      config:
        type: BarplotResponseConfig