#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  MapMarkersOverlayPostRequest:
    type: VisualizationRequestBase
    properties:
      config: MapMarkersOverlaySpec
  
  MapMarkersOverlaySpec:
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      showMissingness:
        type: ShowMissingness
        required: false
      xAxisVariable: 
        type: VariableSpec
      geoAggregateVariable: 
        type: VariableSpec
      valueSpec: 
        type: ValueSpec
      longitudeVariable?:
        type: VariableSpec
      latitudeVariable?:
        type: VariableSpec
      viewport?:
        type: GeolocationViewport

  MapMarkersOverlayConfig:
    type: PlotConfig
    properties:
      viewport:
        type: GeolocationViewport

  MapMarkersOverlay:
    additionalProperties: false
    properties:
      data:
        type: MapMarkersOverlayData[]
      config:
        type: MapMarkersOverlayConfig

  MapMarkersOverlayPostResponse:
    additionalProperties: false
    properties:
      mapMarkers:
        type: MapMarkersOverlay
      sampleSizeTable:
        type: SampleSizeTable[]
      completeCasesTable:
        type: VariableCompleteCases[]
