#%RAML 1.0 Library

types:

  DateHistogramBinWidthPostRequest:
    type: HistogramPostRequest
    properties:
      config: DateHistogramBinWidthSpec

  DateHistogramBinWidthSpec:
    type: HistogramSpec
    properties:
      binWidth:
        type: string
        required: false
      viewportMin:
        type: string
        required: false
      viewportMax:
        type: string
        required: false
  
  DateHistogramBinWidthSummary:
    properties:
      min:
        type: string
      q1:
        type: string
      median:
        type: string
      mean:
        type: string
      q3:
        type: string
      max:
        type: string
                
  DateHistogramBinWidthViewportResponse:
    properties:
      xMin:
        type: string
      xMax:
        type: string
        
  DateHistogramBinWidthConfig:
    type: HistogramResponseConfig
    properties:
      binWidth: 
        type: string
      summary:
        type: DateHistogramBinWidthSummary
      viewport:
        type: DateHistogramBinWidthViewportResponse
        
  DateHistogramBinWidthPostResponse:
    additionalProperties: false
    properties:
      data:
        type: HistogramResponseData[]
      config:
        type: DateHistogramBinWidthConfig
