#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  TwoByTwoStatsTable:
    additionalProperties: false
    properties:
      facetVariableDetails:
        type: StrataVariableDetails[]
        maxItems: 2
        required: false
      oddsratio:
        type: number[]
      pvalue:
        type: number[]
      orInterval:
        type: string[]
      relativerisk:
        type: number[]
      rrInterval:
        type: string[]
        
  TwoByTwoPostResponse:
    additionalProperties: false
    properties:
      mosaic:
        type: Mosaic
      sampleSizeTable:
        type: SampleSizeTable[]
      statsTable:
        type: TwoByTwoStatsTable[]