#%RAML 1.0 Library

types:

  ###################################################
  ###  Subset Filter Types
  ###################################################

  API_Filter:
    type: object
    discriminator: type
    properties:
      entityId: string
      type: API_FilterType

  API_FilterType:
    enum: [ 'stringSet', 'numberSet', 'dateSet', 'numberRange', 'dateRange', 'longitudeRange', 'multiFilter' ]

  API_BooleanOperationType:
    enum: [ 'intersect', 'union' ]

  API_MultiFilterSubFilter:
    type: object
    properties:
      variableId: string
      stringSet: string[]

  API_MultiFilter:
    type: API_Filter
    discriminatorValue: 'multiFilter'
    properties:
      operation: API_BooleanOperationType
      variableId: string
      subFilters: API_MultiFilterSubFilter[]

  API_StringSetFilter:
    type: API_Filter
    discriminatorValue: 'stringSet'
    properties:
      variableId: string
      stringSet: string[]

  API_NumberSetFilter:
    type: API_Filter
    discriminatorValue: 'numberSet'
    properties:
      variableId: string
      numberSet: number[]

  API_DateSetFilter:
    type: API_Filter
    discriminatorValue: 'dateSet'
    properties:
      variableId: string
      dateSet: string[]   # how to constrain this to a date?

  API_NumberRangeFilter:
    type: API_Filter
    discriminatorValue: 'numberRange'
    properties:
      variableId: string
      min: number
      max: number

  API_DateRangeFilter:
    type: API_Filter
    discriminatorValue: 'dateRange'
    properties:
      variableId: string
      min: string
      max: string

  API_LongitudeRangeFilter:
    type: API_Filter
    discriminatorValue: 'longitudeRange'
    properties:
      variableId: string
      left: number
      right: number
