package org.veupathdb.service.eda.merge.plugins;

import org.veupathdb.service.eda.merge.core.derivedvars.DerivedVariableFactory;
import org.veupathdb.service.eda.merge.core.derivedvars.Reduction;
import org.veupathdb.service.eda.merge.plugins.reductions.Mean;
import org.veupathdb.service.eda.merge.plugins.reductions.RelativeObservationAggregator;
import org.veupathdb.service.eda.merge.plugins.reductions.SubsetMembership;
import org.veupathdb.service.eda.merge.plugins.reductions.Sum;

import static org.veupathdb.service.eda.merge.core.derivedvars.DerivedVariableFactory.pluginsOf;

/**
 * Provides the definitive list of reduction derived variables which may be generated by this service
 */
public class Reductions {
  public static DerivedVariableFactory.PluginMap<Reduction> getPlugins() {
    return pluginsOf(Reduction.class,
        // available reductions
        Sum.class,
        Mean.class,
        SubsetMembership.class,
        RelativeObservationAggregator.class
    );
  }
}
