#%RAML 1.0 Library

types:

  CorrelationBipartitenetworkSpec:
    additionalProperties: false
    properties:
      significanceThreshold:
        type: number
        required: false
      correlationCoefThreshold:
        type: number
        required: false

  CorrelationBipartiteNetworkPostResponse:
    additionalProperties: false
    type: BipartiteNetworkPostResponse
    properties:
      significanceThreshold: number
      correlationCoefThreshold: number