#%RAML 1.0 Library

types:

  CorrelationNetworkSpec:
    additionalProperties: false
    properties:
      significanceThreshold:
        type: number
        required: false
      correlationCoefThreshold:
        type: number
        required: false
      layout?:
        type: string
        enum: ['none','force','circle','nicely']

  CorrelationBipartiteNetworkPostResponse:
    additionalProperties: false
    type: BipartiteNetworkPostResponse
    properties:
      significanceThreshold: number
      correlationCoefThreshold: number

  CorrelationNetworkPostResponse:
    additionalProperties: false
    type: NetworkPostResponse
    properties:
      significanceThreshold: number
      correlationCoefThreshold: number