#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  AnalysesGetResponse:
    additionalProperties: false
    properties:
      analyses: AnalysisOverview[]

  AnalysisOverview:
    properties:
      name: string

  AnalysisRequestBase:
    additionalProperties: false
    properties:
      studyId: string
      subset:
        required: false
        type: API_Filter[]
      derivedVariables:
        required: false
        type: DerivedVariable[]
