#%RAML 1.0 Library

types:

  AppsGetResponse:
    properties:
      apps: AppOverview[]

  AppOverview:
    additionalProperties: false
    properties:
      name: string
      displayName: string
      description: string
      projects: string[]
      visualizations: VisualizationOverview[]

  VisualizationDataElementConstraint:
    additionalProperties: false
    properties:
      isRequired:
        type: boolean
      isTemporal:
        type: boolean
      minNumVars:
        type: number
      maxNumVars:
        type: number
      maxNumValues:
        type: number
      allowedTypes:
        type: API_VariableType[]
        required: false
      allowedShapes:
        type: API_VariableDataShape[]
        required: false
      description:
        type: string

  VisualizationDataElementConstraintPattern:
    properties:
      //: VisualizationDataElementConstraint

  VisualizationOverview:
    additionalProperties: false
    properties:
      name: string
      displayName: string
      description: string
      projects: string[]
      maxPanels: number
      dataElementConstraints:
        type: VisualizationDataElementConstraintPattern[]
        required: false
      dataElementDependencyOrder:
        type: string[]
        required: false
      # inputSchema: object  (TBD)
      # outputSchema: object (TBD)
