#%RAML 1.0 Library

types:

  AppsGetResponse:
    properties:
      apps: AppOverview[]

  AppOverview:
    additionalProperties: false
    properties:
      name: string
      displayName: string
      description: string
      visualizations: VisualizationOverview[]

  VisualizationOverview:
    additionalProperties: false
    properties:
      name: string
      displayName: string
      description: string
      # inputSchema: object  (TBD)
      # outputSchema: object (TBD)
