#%RAML 1.0 Library

types:

  AppsGetResponse:
    properties:
      apps: AppOverview[]

  AppOverview:
    additionalProperties: false
    properties:
      name: string
      displayName: string
      description: string
      projects: string[]
      computeName?: string
      visualizations: VisualizationOverview[]

  VisualizationDataElementConstraint:
    additionalProperties: false
    properties:
      isRequired:
        type: boolean
      isTemporal:
        type: boolean
      minNumVars:
        type: number
      maxNumVars:
        type: number
      maxNumValues:
        type: number
      allowedTypes:
        type: API_VariableType[]
        required: false
      allowedShapes:
        type: API_VariableDataShape[]
        required: false
      description:
        type: string

  VisualizationDataElementConstraintPattern:
    properties:
      //: VisualizationDataElementConstraint

  # only really need this when value is false i suppose
  # the key should be a usual suspect for the particular viz
  # ex:  usual scatter plot has a valueSpec, beta div scatter will not
  # for beta div scatter key 'valueSpec' should have a value of 'false'
  # this leaves us very flexible, but also possible to put nonsense in here
  # alternative might be defining unique configs for each plot type explicitly
  BooleanMap:
    additionalProperties: false
    properties: 
      key: string 
      value: boolean

  VisualizationOverview:
    additionalProperties: false
    properties:
      name: string
      displayName: string
      description: string
      projects: string[]
      maxPanels: number
      config: 
        type: BooleanMap[]
        required: false
      dataElementConstraints:
        type: VisualizationDataElementConstraintPattern[]
        required: false
      dataElementDependencyOrder:
        type: string[]
        required: false
      # inputSchema: object  (TBD)
      # outputSchema: object (TBD)
