#%RAML 1.0 Library

types:

  API_Filter:
    type: object
    discriminator: type
    properties:
      entityId: string
      variableId: string
      type: API_FilterType

  API_FilterType:
    enum: [ 'stringSet', 'numberSet', 'dateSet', 'numberRange', 'dateRange' ]

  API_StringSetFilter:
    type: API_Filter
    discriminatorValue: 'stringSet'
    properties:
      stringSet: string[]

  API_NumberSetFilter:
    type: API_Filter
    discriminatorValue: 'numberSet'
    properties:
      numberSet: number[]

  API_DateSetFilter:
    type: API_Filter
    discriminatorValue: 'dateSet'
    properties:
      dateSet: string[]   # how to constrain this to a date?

  API_NumberRangeFilter:
    type: API_Filter
    discriminatorValue: 'numberRange'
    properties:
      min: number
      max: number

  API_DateRangeFilter:
    type: API_Filter
    discriminatorValue: 'dateRange'
    properties:
      min: string
      max: string
