#%RAML 1.0 Library

types:
  
  ContinuousVariableMetadataPostRequest:
    additionalProperties: false
    type: VisualizationRequestBase
    properties:
      config: ContinuousVariableMetadataSpec

  ContinuousVariableMetadataSpec:
    additionalProperties: false
    properties:
      variableId : VariableSpec
      metadata:
        # is this valid? im guessing how wed do this..
        type: array
        items:
          enum: ['binRanges', 'median']

  # TODO should the BinRange and BinRangeWithValue live somewhere else?
  BinRange:
    additionalProperties: false
    properties:
      binStart: string # number | date
      binEnd: string # number | date
      binLabel: string

  BinRangeWithValue:
    additionalProperties: false
    type: BinRange
    properties:
      value: number

  AllBinRanges:
    additionalProperties: false
    properties:
      equalInterval: BinRange[]
      quantile: BinRange[]
      standardDeviation: BinRange[]

  ContinuousVariableMetadataPostResponse:
    additionalProperties: false
    properties:
      binRanges?: AllBinRanges
      median?: number
