#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  Node:
    properties:
      id: string
  
  Link:
    properties:
      source: Node
      target: Node
      strokeWidth: string
      color: string
  
  Network:
    properties:
      nodes: Node[]
      links: Link[]

  BipartiteNetwork:
    type: Network
    properties:
      column1NodeIDs: string[]
      column2NodeIDs: string[]