#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  BarplotPostRequest:
    type: AnalysisRequestBase
    properties:
      config: BarplotSpec

  BarplotSpec:
    additionalProperties: false
    properties:
      entityId:
        type: string
      valueSpec:
        type: string
        enum: ['identity', 'count']
      xAxisVariable: 
        type: VariableSpec
      overlayVariable: 
        type: VariableSpec
        required: false
      facetVariable: 
        type: VariableSpec[]
        maxItems: 2
        required: false

  BarplotData:
    additionalProperties: false
    properties:
      overlayVariableDetails:
        type: StrataVariableDetails
        required: false
      facetVariableDetails:
        type: StrataVariableDetails[]
        maxItems: 2
        required: false
      value:
        type: number[]
        minItems: 1
        required: true
      label:
        type: string[]
        minItems: 1
        required: true

  BarplotConfig:
    type: VisualizationConfig
    properties:
      xVariableDetails:
        type: VariableSpec

  BarplotPostResponse:
    additionalProperties: false
    properties:
      data:
        type: BarplotData[]
      config:
        type: BarplotConfig