#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  MosaicPostRequest:
    type: AnalysisRequestBase
    properties:
      config: MosaicSpec

  MosaicSpec:
    additionalProperties: false
    properties:
      entityId:
        type: string
      xAxisVariable: 
        type: VariableSpec
      yAxisVariable: 
        type: VariableSpec
      facetVariable: 
        type: VariableSpec[]
        maxItems: 2
        required: false

# TODO make sure the response props have the right names, includes table values if needed etc
# Currently, i just replicated bar plot, since they are visually similar. needs more thought

  MosaicPostResponse:
    additionalProperties: false
    properties:
      group:
        type: string
        required: false
      panel:
        type: string
        required: false
      value:
        type: number[]
        minItems: 1
        required: true
      label:
        type: string[]
        minItems: 1
        required: true