#%RAML 1.0 Library

types:

  RecordCountPostRequest:
    type: BaseAnalysisConfig
    properties:
      config: RecordCountSpec

  RecordCountSpec:
    additionalProperties: false
    type: object

  RecordCountPostResponse:
    additionalProperties: false
    properties:
      recordCount: number
