#%RAML 1.0 Library

types:

  HistogramPostRequest:
    type: AnalysisRequestBase
    properties:
      config: HistogramSpec

  NumericBinWidth:
    properties:
      type: number
    
  DateBinWidth:
    properties:
      type: string

  HistogramSpec:
    additionalProperties: false
    properties:
      entityId:
        type: string
      xAxisVariable:
        type: string
      binWidth:
        type: NumericBinWidth | DateBinWidth
        required: false
      valueSpec: 
        type: string
        enum: ['count', 'proportion']
      overlayVariable: 
        type: string
        required: false
      facetVariable: 
        type: string[]
        maxItems: 2
        required: false

  HistogramPostResponse:
    additionalProperties: false
    properties:
      group:
        type: string
        required: false
      panel:
        type: string
        required: false
      value:
        type: number[]
        minItems: 1
        required: true
      binStart:
      	type: string[]
      	minItems: 1
      	required: true
      binLabel:
        type: string[]
        minItems: 1
        required: true
