#%RAML 1.0 Library

types:

  DateHistogramBinWidthPostRequest:
    type: HistogramPostRequest
    properties:
      config: DateHistogramBinWidthSpec

  DateHistogramBinWidthSpec:
    type: HistogramSpec
    properties:
      binWidth:
        type: string
        required: false
      viewportMin:
        type: string
        required: false
      viewportMax:
        type: string
        required: false
  
  DateHistogramBinWidthConfig:
    type: HistogramConfig
    properties:
      binWidth: 
        type: number
        
  DateHistogramBinWidthPostResponse:
    additionalProperties: false
    properties:
      data:
        type: HistogramData[]
      config:
        type: DateHistogramBinWidthConfig