#%RAML 1.0 Library

types:

  MapPostRequest:
    type: AnalysisRequestBase
    properties:
      config: RecordCountSpec

  MapSpec:
    additionalProperties: false
    type: object
    properties:
      entityId: 
        type: string
      geoAggregateVariable:
        type: string

  MapPostResponse:
    additionalProperties: false
    properties:
      geoAggregateValue:
        type: string
      entityCount:
        type: number
      avgLat:
        type: number
      avgLon:
        type: number
      minLat:
        type: number
      minLon:
        type: number
      maxLat:
        type: number
      maxLon:
        type: number
