#%RAML 1.0 Library

types:

  HistogramPostRequest:
    type: AnalysisRequestBase

  ValueSpec:
    type: string
    enum: ['count', 'proportion']

  HistogramSpec:
    additionalProperties: false
    properties:
      entityId:
        type: string
      xAxisVariable:
        type: VariableSpec
      valueSpec: 
        type: ValueSpec
      overlayVariable: 
        type: VariableSpec
        required: false
      facetVariable: 
        type: VariableSpec[]
        maxItems: 2
        required: false

  HistogramPostResponse:
    additionalProperties: false
    properties:
      group:
        type: string
        required: false
      panel:
        type: string
        required: false
      value:
        type: number[]
        minItems: 1
        required: true
      binStart:
        type: string[]
        minItems: 1
        required: true
      binLabel:
        type: string[]
        minItems: 1
        required: true