#%RAML 1.0 Library

types:

  HistogramPostRequest:
    type: AnalysisRequestBase

  ValueSpec:
    type: string
    enum: ['count', 'proportion']

  HistogramSpec:
    additionalProperties: false
    properties:
      entityId:
        type: string
      xAxisVariable:
        type: VariableSpec
      valueSpec: 
        type: ValueSpec
      overlayVariable: 
        type: VariableSpec
        required: false
      facetVariable: 
        type: VariableSpec[]
        maxItems: 2
        required: false
   

  HistogramData:
    additionalProperties: false
    properties:
      overlayVariableDetails:
        type: StrataVariableDetails
        required: false
      facetVariableDetails:
        type: StrataVariableDetails[]
        maxItems: 2
        required: false
      value:
        type: number[]
        minItems: 1
        required: true
      binStart:
        type: string[]
        minItems: 1
        required: true
      binLabel:
        type: string[]
        minItems: 1
        required: true
        
  BinSlider:
    additionalProperties: false
    properties:
      min:
        type: number
      max:
        type: number
      step:
        type: number
        
  HistogramConfig:
    type: VisualizationConfig
    properties:
      binSlider:
        type: BinSlider
      xVariableDetails:
        type: VariableSpec
      

  HistogramPostResponse:
    additionalProperties: false
    properties:
      data:
        type: HistogramData[]
      config:
        type: HistogramConfig
        
    