#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  BoxplotPostRequest:
    type: AnalysisRequestBase
    properties:
      config: BoxplotSpec

  BoxplotSpec:
    additionalProperties: false
    properties:
      entityId:
        type: string
      points:
        type: string
        enum: ['outliers', 'all']
      mean:
        type: string
        enum: ['true', 'false']
      xAxisVariable: 
        type: VariableSpec
      yAxisVariable: 
        type: VariableSpec
      overlayVariable: 
        type: VariableSpec
        required: false
      facetVariable: 
        type: VariableSpec[]
        maxItems: 2
        required: false

  BoxplotPostResponse:
    additionalProperties: false
    properties:
      group:
        type: string
        required: false
      panel:
        type: string
        required: false
      lowerfence:
        type: number[]
        minItems: 1
        required: true
      upperfence:
        type: number[]
        minItems: 1
        required: true
      q1:
        type: number[]
        minItems: 1
        required: true
      q3:
        type: number[]
        minItems: 1
        required: true
      median:
        type: number[]
        minItems: 1
        required: true
      outliers:
        type: number[][]
        required: false
      rawData:
        type: number[][]
        required: false
      mean:
        type: number[]
        required: false