#%RAML 1.0 Library

types:

  DateHistogramNumBinsPostRequest:
    type: HistogramPostRequest
    properties:
      config: DateHistogramNumBinsSpec

  DateHistogramNumBinsSpec:
    type: HistogramSpec
    properties:
      numBins:
        type: number
        required: false
      viewportMin:
        type: string
      viewportMax:
        type: string
        
  DateHistogramNumBinsPostResponse:
    type: HistogramPostResponse
    properties:
      numBins:
        type: number