#%RAML 1.0 Library

types:

  NumericHistogramBinWidthPostRequest:
    type: HistogramPostRequest
    properties:
      config: NumericHistogramBinWidthSpec

  NumericHistogramBinWidthSpec:
    type: HistogramSpec
    properties:
      binWidth:
        type: number
        required: false
      viewportMin:
        type: number
        required: false
      viewportMax:
        type: number
        required: false
        
  NumericHistogramBinWidthPostResponse:
    type: HistogramPostResponse
    properties:
      binWidth:
        type: number