#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  ScatterplotPostRequest:
    type: VisualizationRequestBase
    properties:
      config: ScatterplotSpec

  ScatterplotSpec:
    additionalProperties: false
    properties:
      entityId:
        type: string
      valueSpec:
        type: string
        enum: ['smoothedMean', 'density', 'raw']
      xAxisVariable: 
        type: VariableSpec
      yAxisVariable: 
        type: VariableSpec
      overlayVariable: 
        type: VariableSpec
        required: false
      facetVariable: 
        type: VariableSpec[]
        maxItems: 2
        required: false

  ScatterplotData:
    additionalProperties: false
    properties:
      overlayVariableDetails:
        type: StrataVariableDetails
        required: false
      facetVariableDetails:
        type: StrataVariableDetails[]
        maxItems: 2
        required: false
      seriesY:
        type: number[]
        minItems: 1
      seriesX:
        type: number[]
        minItems: 1
      intervalX:
        type: number[]
        required: false
      intervalY:
        type: number[]
        required: false
      intervalSE:
        type: number[]
        required: false
      densityX:
        type: number[]
        required: false
      densityY:
        type: number[]
        required: false

  ScatterplotConfig:
    type: VisualizationConfig
    properties:
      xVariableDetails:
        type: VariableSpec
      yVariableDetails:
        type: VariableSpec

  ScatterplotPostResponse:
    additionalProperties: false
    properties:
      data:
        type: ScatterplotData[]
      config:
        type: ScatterplotConfig