#%RAML 1.0 Library

types:

  DateHistogramBinWidthPostRequest:
    type: HistogramPostRequest
    properties:
      config: DateHistogramBinWidthSpec

  DateHistogramBinWidthSpec:
    type: HistogramSpec
    properties:
      binWidth:
        type: string
        required: false
      viewportMin:
        type: string
        required: false
      viewportMax:
        type: string
        required: false
        
  DateHistogramBinWidthPostResponse:
    type: HistogramPostResponse
    properties:
      binWidth:
        type: string