#%RAML 1.0 Library

types:

  EntityCountPostRequest:
    additionalProperties: false
    properties:
      filters: API_Filter[]

  EntityCountPostResponse:
    additionalProperties: false
    properties:
      count: integer

  VariableCountPostRequest:
    additionalProperties: false
    properties:
      filters: API_Filter[]

  VariableCountPostResponse:
    additionalProperties: false
    properties:
      count: integer

  VariableDistributionPostRequest:
    additionalProperties: false
    properties:
      filters: API_Filter[]

  VariableDistributionPostResponse:
    additionalProperties: false
    properties:
      counts: API_HistogramTuple[]

  EntityTabularPostRequest:
    additionalProperties: false
    properties:
      outputVariableIds: string[]
      filters: API_Filter[]

  EntityTabularPostResponse:
    additionalProperties: false
    properties:
      counts: string[][]

  API_HistogramTuple:
    type: object
    properties:
      value: string
      count: integer
