#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  VisualizationRequestBase:
    additionalProperties: false
    properties:
      studyId: string
      filters:
        required: false
        type: API_Filter[]
      derivedVariables:
        required: false
        type: DerivedVariable[]

  StrataVariableDetails:
    type: VariableSpec
    properties:
      value: string

  BinSpec:
    additionalProperties: false
    properties:
      type?:
        type: string
        enum: ['binWidth','numBins']
      value?: number
      units?: BinUnits

  XAxisViewport:
    additionalProperties: false
    properties:
      xMin:
        type: string
      xMax:
        type: string

  ErrorBar:
    additionalProperties: false
    properties:
      lowerBound: number
      upperBound: number
      error: string

  SimpleSampleSize:
    additionalProperties: false
    properties:
      N: number

  ProportionSampleSize:
    additionalProperties: false
    properties:
      numeratorN: number
      denominatorN: number
  
  SampleSize:
    type: SimpleSampleSize | ProportionSampleSize

  ShowMissingness:
    type: string
    enum: ['allVariables', 'strataVariables', 'noVariables']

  ShowMissingnessNoAxes:
    type: string
    enum: ['strataVariables', 'noVariables']

  # Assuming computed variable must be on y axis and that x axis may be determined by collection var or specified.
  BoxplotWith1ComputeSpec:
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      showMissingness:
        type: ShowMissingness
        required: false
      points:
        type: string
        enum: ['outliers', 'all']
      mean:
        type: string
        enum: ['TRUE', 'FALSE']
      computeStats:
        type: string
        enum: ['TRUE', 'FALSE']
      xAxisVariable:
        type: VariableSpec
        required: false
      overlayVariable:
        type: VariableSpec
        required: false
      facetVariable:
        type: VariableSpec[]
        maxItems: 2
        required: false

  # Assume y-axis is always computed variable
  ScatterplotWith1ComputeSpec:
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      showMissingness:
        type: ShowMissingness
        required: false
      valueSpec:
        type: string
        enum: ['raw', 'smoothedMeanWithRaw', 'bestFitLineWithRaw']
      xAxisVariable:
        type: VariableSpec
      overlayVariable: 
        type: VariableSpec
        required: false
      facetVariable:
        type: VariableSpec[]
        maxItems: 2
        required: false
