#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.
  
  VisualizationRequestBase:
    additionalProperties: false
    properties:
      studyId: string
      filters:
        required: false
        type: API_Filter[]
      derivedVariables:
        required: false
        type: DerivedVariable[]
      computeConfig:
        required: false
        type: ComputeConfig
                  
  StrataVariableDetails:
    type: VariableSpec
    properties:
      value: string

  # Should be moved to edacommon -- leaving here until merge for easier iteration
  ComputeConfig:
        type: object
        additionalProperties: false
        properties:
          name: string
          parameters:
            required: false
            type: string[]